### ISSUE TITLE
git xltrail doesn't work, only git-xltrail

### ISSUE THREAD

**Issue by fzumstein** [xlwings/git-xltrail#28]
Under certain circumstances, the `git xltrail` command doesn't seem to work:

Issue Description- Typo in Installation instructions?

Team, on the download page for the Open Source version of xltrail (URL above) the first line of instructions given under “getting Started” is-

C:\>git xltrail install

However this causes an “unknown Git command” error until AFTER xltrail has been installed.

Looking at the executable files installed by xltrail, I believe the command should be-

C:\>git-xltrail install

(note the hyphen instead of a space).

Regards: C Evans

**Comment by incansvl** [comment]
As a guess- if the "git xltrail ..." command relies on adding the xltrail installation folder to the PATH (or the equivalent for Git itself) then the user may need to start a fresh Git command window (CMD or Bash) instead of using one that was already open during the installation.

This is perfectly reasonable, but might be worth making explicit in the documentation.
